export const allCountries = [
    {"countryId":1, "itemName":"Afghanistan"},
    {"countryId":2, "itemName":"Albania"},
    {"countryId":3, "itemName":"Algeria"},
    {"countryId":4, "itemName":"Andorra"},
    {"countryId":5, "itemName":"Angola"},
    {"countryId":6, "itemName":"Antigua and Barbuda"},
    {"countryId":7, "itemName":"Argentina"},
    {"countryId":8, "itemName":"Armenia"},
    {"countryId":9, "itemName":"Australia"},
    {"countryId":10, "itemName":"Austria"},
    {"countryId":11, "itemName":"Azerbaijan"},
    {"countryId":12, "itemName":"Bahamas"},
    {"countryId":13, "itemName":"Bahrain"},
    {"countryId":14, "itemName":"Bangladesh"},
    {"countryId":15, "itemName":"Barbados"},
    {"countryId":16, "itemName":"Belarus"},
    {"countryId":17, "itemName":"Belgium"},
    {"countryId":18, "itemName":"Belize"},
    {"countryId":19, "itemName":"Benin"},
    {"countryId":20, "itemName":"Bhutan"},
    {"countryId":21, "itemName":"Bolivia"},
    {"countryId":22, "itemName":"Bosnia and Herzegovina"},
    {"countryId":23, "itemName":"Botswana"},
    {"countryId":24, "itemName":"Brazil"},
    {"countryId":25, "itemName":"Brunei"},
    {"countryId":26, "itemName":"Bulgaria"},
    {"countryId":27, "itemName":"Burkina Faso"},
    {"countryId":28, "itemName":"Burundi"},
    {"countryId":29, "itemName":"Côte d'Ivoire"},
    {"countryId":30, "itemName":"Cabo Verde"},
    {"countryId":31, "itemName":"Cambodia"},
    {"countryId":32, "itemName":"Cameroon"},
    {"countryId":33, "itemName":"Canada"},
    {"countryId":34, "itemName":"Central African Republic"},
    {"countryId":35, "itemName":"Chad"},
    {"countryId":36, "itemName":"Chile"},
    {"countryId":37, "itemName":"China"},
    {"countryId":38, "itemName":"Colombia"},
    {"countryId":39, "itemName":"Comoros"},
    {"countryId":40, "itemName":"Congo (Congo-Brazzaville"},
    {"countryId":41, "itemName":"Costa Rica"},
    {"countryId":42, "itemName":"Croatia"},
    {"countryId":43, "itemName":"Cuba"},
    {"countryId":44, "itemName":"Cyprus"},
    {"countryId":45, "itemName":"Czechia (Czech Republic"},
    {"countryId":46, "itemName":"Democratic Republic of the Congo"},
    {"countryId":47, "itemName":"Denmark"},
    {"countryId":48, "itemName":"Djibouti"},
    {"countryId":49, "itemName":"Dominica"},
    {"countryId":50, "itemName":"Dominican Republic"},
    {"countryId":51, "itemName":"Ecuador"},
    {"countryId":52, "itemName":"Egypt"},
    {"countryId":53, "itemName":"El Salvador"},
    {"countryId":54, "itemName":"Equatorial Guinea"},
    {"countryId":55, "itemName":"Eritrea"},
    {"countryId":56, "itemName":"Estonia"},
    {"countryId":57, "itemName":"Eswatini (fmr. Swaziland"},
    {"countryId":58, "itemName":"Ethiopia"},
    {"countryId":59, "itemName":"Fiji"},
    {"countryId":60, "itemName":"Finland"},
    {"countryId":61, "itemName":"France"},
    {"countryId":62, "itemName":"Gabon"},
    {"countryId":63, "itemName":"Gambia"},
    {"countryId":64, "itemName":"Georgia"},
    {"countryId":65, "itemName":"Germany"},
    {"countryId":66, "itemName":"Ghana"},
    {"countryId":67, "itemName":"Greece"},
    {"countryId":68, "itemName":"Grenada"},
    {"countryId":69, "itemName":"Guatemala"},
    {"countryId":70, "itemName":"Guinea"},
    {"countryId":71, "itemName":"Guinea-Bissau"},
    {"countryId":72, "itemName":"Guyana"},
    {"countryId":73, "itemName":"Haiti"},
    {"countryId":74, "itemName":"Holy See"},
    {"countryId":75, "itemName":"Honduras"},
    {"countryId":76, "itemName":"Hungary"},
    {"countryId":77, "itemName":"Iceland"},
    {"countryId":78, "itemName":"India"},
    {"countryId":79, "itemName":"Indonesia"},
    {"countryId":80, "itemName":"Iran"},
    {"countryId":81, "itemName":"Iraq"},
    {"countryId":82, "itemName":"Ireland"},
    {"countryId":83, "itemName":"Israel"},
    {"countryId":84, "itemName":"Italy"},
    {"countryId":85, "itemName":"Jamaica"},
    {"countryId":86, "itemName":"Japan"},
    {"countryId":87, "itemName":"Jordan"},
    {"countryId":88, "itemName":"Kazakhstan"},
    {"countryId":89, "itemName":"Kenya"},
    {"countryId":90, "itemName":"Kiribati"},
    {"countryId":91, "itemName":"Kuwait"},
    {"countryId":92, "itemName":"Kyrgyzstan"},
    {"countryId":93, "itemName":"Laos"},
    {"countryId":94, "itemName":"Latvia"},
    {"countryId":95, "itemName":"Lebanon"},
    {"countryId":96, "itemName":"Lesotho"},
    {"countryId":97, "itemName":"Liberia"},
    {"countryId":98, "itemName":"Libya"},
    {"countryId":99, "itemName":"Liechtenstein"},
    {"countryId":100, "itemName":"Lithuania"},
    {"countryId":101, "itemName":"Luxembourg"},
    {"countryId":102, "itemName":"Madagascar"},
    {"countryId":103, "itemName":"Malawi"},
    {"countryId":104, "itemName":"Malaysia"},
    {"countryId":105, "itemName":"Maldives"},
    {"countryId":106, "itemName":"Mali"},
    {"countryId":107, "itemName":"Malta"},
    {"countryId":108, "itemName":"Marshall Islands"},
    {"countryId":109, "itemName":"Mauritania"},
    {"countryId":110, "itemName":"Mauritius"},
    {"countryId":111, "itemName":"Mexico"},
    {"countryId":112, "itemName":"Micronesia"},
    {"countryId":113, "itemName":"Moldova"},
    {"countryId":114, "itemName":"Monaco"},
    {"countryId":115, "itemName":"Mongolia"},
    {"countryId":116, "itemName":"Montenegro"},
    {"countryId":117, "itemName":"Morocco"},
    {"countryId":118, "itemName":"Mozambique"},
    {"countryId":119, "itemName":"Myanmar (formerly Burma"},
    {"countryId":120, "itemName":"Namibia"},
    {"countryId":121, "itemName":"Nauru"},
    {"countryId":122, "itemName":"Nepal"},
    {"countryId":123, "itemName":"Netherlands"},
    {"countryId":124, "itemName":"New Zealand"},
    {"countryId":125, "itemName":"Nicaragua"},
    {"countryId":126, "itemName":"Niger"},
    {"countryId":127, "itemName":"Nigeria"},
    {"countryId":128, "itemName":"North Korea"},
    {"countryId":129, "itemName":"North Macedonia"},
    {"countryId":130, "itemName":"Norway"},
    {"countryId":131, "itemName":"Oman"},
    {"countryId":132, "itemName":"Pakistan"},
    {"countryId":133, "itemName":"Palau"},
    {"countryId":134, "itemName":"Palestine State"},
    {"countryId":135, "itemName":"Panama"},
    {"countryId":136, "itemName":"Papua New Guinea"},
    {"countryId":137, "itemName":"Paraguay"},
    {"countryId":138, "itemName":"Peru"},
    {"countryId":139, "itemName":"Philippines"},
    {"countryId":140, "itemName":"Poland"},
    {"countryId":141, "itemName":"Portugal"},
    {"countryId":142, "itemName":"Qatar"},
    {"countryId":143, "itemName":"Romania"},
    {"countryId":144, "itemName":"Russia"},
    {"countryId":145, "itemName":"Rwanda"},
    {"countryId":146, "itemName":"Saint Kitts and Nevis"},
    {"countryId":147, "itemName":"Saint Lucia"},
    {"countryId":148, "itemName":"Saint Vincent and the Grenadines"},
    {"countryId":149, "itemName":"Samoa"},
    {"countryId":150, "itemName":"San Marino"},
    {"countryId":151, "itemName":"Sao Tome and Principe"},
    {"countryId":152, "itemName":"Saudi Arabia"},
    {"countryId":153, "itemName":"Senegal"},
    {"countryId":154, "itemName":"Serbia"},
    {"countryId":155, "itemName":"Seychelles"},
    {"countryId":156, "itemName":"Sierra Leone"},
    {"countryId":157, "itemName":"Singapore"},
    {"countryId":158, "itemName":"Slovakia"},
    {"countryId":159, "itemName":"Slovenia"},
    {"countryId":160, "itemName":"Solomon Islands"},
    {"countryId":161, "itemName":"Somalia"},
    {"countryId":162, "itemName":"South Africa"},
    {"countryId":163, "itemName":"South Korea"},
    {"countryId":164, "itemName":"South Sudan"},
    {"countryId":165, "itemName":"Spain"},
    {"countryId":166, "itemName":"Sri Lanka"},
    {"countryId":167, "itemName":"Sudan"},
    {"countryId":168, "itemName":"Suriname"},
    {"countryId":169, "itemName":"Sweden"},
    {"countryId":170, "itemName":"Switzerland"},
    {"countryId":171, "itemName":"Syria"},
    {"countryId":172, "itemName":"Tajikistan"},
    {"countryId":173, "itemName":"Tanzania"},
    {"countryId":174, "itemName":"Thailand"},
    {"countryId":175, "itemName":"Timor-Leste"},
    {"countryId":176, "itemName":"Togo"},
    {"countryId":177, "itemName":"Tonga"},
    {"countryId":178, "itemName":"Trinidad and Tobago"},
    {"countryId":179, "itemName":"Tunisia"},
    {"countryId":180, "itemName":"Turkey"},
    {"countryId":181, "itemName":"Turkmenistan"},
    {"countryId":182, "itemName":"Tuvalu"},
    {"countryId":183, "itemName":"Uganda"},
    {"countryId":184, "itemName":"Ukraine"},
    {"countryId":185, "itemName":"United Arab Emirates"},
    {"countryId":186, "itemName":"United Kingdom"},
    {"countryId":187, "itemName":"United States of America"},
    {"countryId":188, "itemName":"Uruguay"},
    {"countryId":189, "itemName":"Uzbekistan"},
    {"countryId":190, "itemName":"Vanuatu"},
    {"countryId":191, "itemName":"Venezuela"},
    {"countryId":192, "itemName":"Vietnam"},
    {"countryId":193, "itemName":"Yemen"},
    {"countryId":194, "itemName":"Zambia"},
    {"countryId":195, "itemName":"Zimbabw"}
];